<?xml version="1.0"?>
<package format="2">
  <name>agilex_swarm_ros_bridge</name>
  <version>0.1.0</version>
  <description>AgileX-specific configuration for swarm_ros_bridge.</description>

  <maintainer email="apt@example.com">XGC2</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>roslaunch</exec_depend>
  <exec_depend>swarm_ros_bridge</exec_depend>

  <export>
  </export>
</package>
