#!/usr/bin/env python
from __future__ import print_function

import argparse
import sys

import rospy
from rospy.msg import AnyMsg


def main():
    parser = argparse.ArgumentParser(description="Wait until one ROS topic publishes a message.")
    parser.add_argument("topic_name")
    parser.add_argument("--timeout", type=float, default=60.0)
    args = parser.parse_args()

    rospy.init_node("xgc2_wait_ros_topic", anonymous=True, disable_signals=True)
    try:
        rospy.wait_for_message(args.topic_name, AnyMsg, timeout=args.timeout)
        return 0
    except Exception as exc:
        print("ROS topic %s did not publish within %.1fs: %s" % (
            args.topic_name,
            args.timeout,
            exc,
        ), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
