#!/usr/bin/env python
# VRPN -> /pose_raw + world->base_link. Display only.
# Does not publish /cmd_vel, /pose, or vision_pose.
from __future__ import print_function

import math

import rospy
import tf
from geometry_msgs.msg import PoseStamped


def _finite_pose(position, orientation):
    vals = (
        position.x,
        position.y,
        position.z,
        orientation.x,
        orientation.y,
        orientation.z,
        orientation.w,
    )
    if not all(math.isfinite(v) for v in vals):
        return False
    n2 = (
        orientation.x * orientation.x
        + orientation.y * orientation.y
        + orientation.z * orientation.z
        + orientation.w * orientation.w
    )
    return n2 > 1e-6


class VrpnVizTf(object):
    def __init__(self):
        self.world_frame = rospy.get_param("~world_frame", "world")
        self.mocap_frame = rospy.get_param("~mocap_frame", "base_link")
        tracker = rospy.get_param("~tracker", "pose_0")
        prefix = rospy.get_param("~vrpn_prefix", "/vrpn_client_node")
        pose_in = rospy.get_param("~pose_in", "{}/{}/pose".format(prefix, tracker))
        pose_raw = rospy.get_param("~pose_raw_topic", "/pose_raw")

        self.br = tf.TransformBroadcaster()
        self.pose_pub = rospy.Publisher(pose_raw, PoseStamped, queue_size=1)
        rospy.Subscriber(pose_in, PoseStamped, self.on_vrpn, queue_size=1)
        rospy.loginfo(
            "vrpn_viz_tf tracker=%s in=%s raw=%s tf %s->%s",
            tracker,
            pose_in,
            pose_raw,
            self.world_frame,
            self.mocap_frame,
        )

    def on_vrpn(self, msg):
        if not _finite_pose(msg.pose.position, msg.pose.orientation):
            return
        out = PoseStamped()
        out.header.stamp = msg.header.stamp
        out.header.frame_id = self.world_frame
        out.pose = msg.pose
        self.pose_pub.publish(out)
        stamp = msg.header.stamp
        if stamp is None or stamp.is_zero():
            stamp = rospy.Time.now()
        p = msg.pose.position
        q = msg.pose.orientation
        self.br.sendTransform(
            (p.x, p.y, p.z),
            (q.x, q.y, q.z, q.w),
            stamp,
            self.mocap_frame,
            self.world_frame,
        )


def main():
    rospy.init_node("vrpn_viz_tf")
    VrpnVizTf()
    rospy.spin()


if __name__ == "__main__":
    main()
